//! AES-256-GCM encrypted-ingest tests (H1 parity with the Python agent).
//!
//! The fixture vectors in `fixtures/encryption_vectors.json` were
//! generated by running `guard_agent/encryption.py` (Python 3.14,
//! cryptography 50.0.1) with monkeypatched `os.urandom` nonces, so each ciphertext is a byte-exact
//! cross-language pin: these tests must decrypt them, and the canonical
//! JSON serializer must reproduce the Python plaintext bytes.

use guard_agent_rs::{AgentConfig, GuardAgent, PayloadEncryptor, SecurityEvent, canonical_json};
use serde_json::Value;
use wiremock::matchers::{method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

const VECTORS_JSON: &str = include_str!("fixtures/encryption_vectors.json");

fn vectors() -> Vec<Value> {
    serde_json::from_str(VECTORS_JSON).expect("vector fixtures parse")
}

#[test]
fn decrypts_every_python_generated_vector() {
    let vectors = vectors();
    assert_eq!(vectors.len(), 4);
    for (index, vector) in vectors.iter().enumerate() {
        let encryptor = PayloadEncryptor::new(vector["key_b64"].as_str().unwrap()).unwrap();
        let decrypted = encryptor
            .decrypt(
                vector["ciphertext_b64"].as_str().unwrap(),
                vector["aad"].as_str(),
            )
            .unwrap();
        let expected: Value =
            serde_json::from_str(vector["plaintext_json"].as_str().unwrap()).unwrap();
        assert_eq!(decrypted, expected, "vector {index}");
    }
}

#[test]
fn canonical_json_is_byte_identical_to_python() {
    for vector in vectors() {
        let parsed: Value =
            serde_json::from_str(vector["plaintext_json"].as_str().unwrap()).unwrap();
        assert_eq!(
            canonical_json(&parsed),
            vector["plaintext_json"].as_str().unwrap()
        );
    }
}

#[test]
fn rejects_tampered_ciphertext() {
    let vectors = vectors();
    let encryptor = PayloadEncryptor::new(vectors[0]["key_b64"].as_str().unwrap()).unwrap();
    let tampered = vectors[0]["tampered_ciphertext_b64"].as_str().unwrap();
    assert!(encryptor.decrypt(tampered, None).is_err());
}

#[test]
fn rejects_aad_mismatch() {
    let vectors = vectors();
    let encryptor = PayloadEncryptor::new(vectors[3]["key_b64"].as_str().unwrap()).unwrap();
    let ciphertext = vectors[3]["ciphertext_b64"].as_str().unwrap();
    assert!(encryptor.decrypt(ciphertext, Some("wrong")).is_err());
    assert!(encryptor.decrypt(ciphertext, Some("batch-123")).is_ok());
}

#[test]
fn rejects_empty_and_undersized_keys() {
    assert!(PayloadEncryptor::new("").is_err());
    assert!(PayloadEncryptor::new("AAAA").is_err());
}

#[test]
fn round_trip_and_padded_output() {
    let vectors = vectors();
    let encryptor = PayloadEncryptor::new(vectors[0]["key_b64"].as_str().unwrap()).unwrap();
    let data = serde_json::json!({
        "events": [{"event_type": "rate_limit", "ip_address": "1.2.3.4"}],
        "metrics": [],
        "zeta": 1,
        "unicode": "h\u{e9}llo",
    });
    let encrypted = encryptor.encrypt(&data, None).unwrap();
    assert_eq!(
        encrypted.len() % 4,
        0,
        "output must be padded urlsafe base64"
    );
    assert_eq!(encryptor.decrypt(&encrypted, None).unwrap(), data);
}

#[tokio::test]
async fn routes_batches_to_the_encrypted_endpoint_with_the_python_envelope() {
    let server = MockServer::start().await;
    Mock::given(method("POST"))
        .and(path("/api/v1/events/encrypted"))
        .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
            "success": true,
            "events_received": 1,
            "events_processed": 1,
            "metrics_received": 0,
            "metrics_processed": 0,
            "errors": [],
        })))
        .mount(&server)
        .await;

    let mut config = AgentConfig::new("test-api-key-1234");
    config.endpoint = server.uri();
    config.install_id = Some("install-test-0001".to_owned());
    config.retry_attempts = 0;
    config.project_encryption_key = Some(vectors()[0]["key_b64"].as_str().unwrap().to_owned());
    let agent = GuardAgent::new(config).unwrap();

    agent
        .send_event(SecurityEvent::new("rate_limited").with_ip_address("10.0.0.1"))
        .await;
    agent.flush_buffer().await;

    let requests: Vec<serde_json::Value> = server
        .received_requests()
        .await
        .unwrap()
        .into_iter()
        .filter(|request| request.url.path() == "/api/v1/events/encrypted")
        .map(|request| serde_json::from_slice(&request.body).unwrap())
        .collect();
    assert_eq!(requests.len(), 1, "exactly one encrypted request");

    let envelope = &requests[0];
    let mut keys = envelope
        .as_object()
        .unwrap()
        .keys()
        .cloned()
        .collect::<Vec<_>>();
    keys.sort();
    assert_eq!(
        keys,
        vec![
            "agent_version",
            "batch_id",
            "encrypted_payload",
            "guard_core_version",
            "guard_version"
        ]
    );

    // Server-side decrypt: the envelope opens under the configured key.
    let encryptor = PayloadEncryptor::new(vectors()[0]["key_b64"].as_str().unwrap()).unwrap();
    let inner = encryptor
        .decrypt(envelope["encrypted_payload"].as_str().unwrap(), None)
        .unwrap();
    assert_eq!(
        inner
            .as_object()
            .unwrap()
            .keys()
            .cloned()
            .collect::<Vec<_>>(),
        vec!["events", "metrics"]
    );
    assert_eq!(inner["events"].as_array().unwrap().len(), 1);
}

#[tokio::test]
async fn fails_startup_without_plaintext_fallback_on_invalid_key() {
    let mut config = AgentConfig::new("test-api-key-1234");
    config.project_encryption_key = Some("not-a-valid-key".to_owned());
    assert!(GuardAgent::new(config).is_err());
}
